---
title: "NYC Restaurant Inspection Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("rest_inspec")

rest_inspec =
  rest_inspec |> 
  select(-action, -camis, -phone, -inspection_type, -record_date) |> 
  filter(
    !is.na(grade),
    !is.na(violation_code),
    !is.na(boro),
    grade != "Not Yet Graded",
    boro != "Missing")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Number of restaurants by borough separated by grade

```{r, warning = FALSE}
rest_inspec |> 
  group_by(grade) |> 
  count(boro) |> 
  plot_ly(y = ~n, x = ~boro, color = ~grade, type = "bar", colors = "viridis") |> 
  layout(xaxis = list(type = 'category'), barmode = 'stack')
```


Column {data-width=350}
-----------------------------------------------------------------------

### Score of restaurants by borough.

```{r, warning = FALSE}
rest_inspec |> 
  mutate(boro = fct_reorder(boro, score)) |> 
  plot_ly(y = ~score, color = ~boro, type = "box", colors = "viridis")
```

### Scatterplot of restaurant scores over time in Manhattan
```{r, warning = FALSE}
rest_inspec |> 
  filter(cuisine_description == "American") |> 
  plot_ly(
    x = ~grade_date, y = ~score, type = "scatter", mode = "markers", color = ~boro, alpha = 0.5)
```


